apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-publisher
  namespace: apps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-publisher
  template:
    metadata:
      labels:
        app: demo-publisher
    spec:
      containers:
        - name: demo-publisher
          image: demo-publisher:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SERVER_CONTEXT_PATH
              value: "/demo-publisher/v1"

            - name: AWS_REGION
              value: "us-east-1"
            - name: AWS_ENDPOINT
              value: "http://localstack:4566"
            - name: AWS_ACCESS_KEY
              value: "test"
            - name: AWS_SECRET_KEY
              value: "test"

            - name: AWS_SNS_TOPIC_ARN
              value: "arn:aws:sns:us-east-1:000000000000:generic-topic"

            # Vari√°veis para limitar a heap da JVM
            - name: JAVA_XMS
              value: "256m"
            - name: JAVA_XMX
              value: "384m"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-publisher
  namespace: apps
spec:
  selector:
    app: demo-publisher
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
